---
deployment:
  tasks:
    - export DEPLOYPATH=/home/impaktom14266d67/public_html/
    - /bin/cp -r . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -f $DEPLOYPATH/.env.example
    - /bin/rm -f $DEPLOYPATH/CHANGELOG.md
    - /bin/rm -f $DEPLOYPATH/README.md
